import random


user_diff_level = input("""
Please select 1, 2 or 3.
1 ===> Easy 😁
2 ===> Medium 😐
3 ===> Hard 😫
Select an option:
""")
difficulty = {'easy': '1', 'medium': '2', 'Hard': '3'}
random_value = ''

"""
This function uses are; if the user inputs a number and the user number is more or less than the value 
randomly generated by the program, the user will be informed. Also, the user will be informed on how many trials they 
have left. If the user trial finishes before the user gets the randomly generated value, the program will stop running, 
and will inform the user the game is over displaying the randomly generated value. If the user gets the randomly
generated value before their trial ends, the program also stops and inform the user that they won.

"""


def count():

    guess_count = 0
    while guess_count < guess_limit:
        user_guess = int(input("\nGuess the number: "))
        guess_count += 1

        if user_guess == value:
            print("\nHurray!!!\nYou won.")
            break

        elif user_guess != value:
            print("\nWrong!!!")

            if user_guess > value:
                print("Your guess is too high 😢.")

                if guess_limit - guess_count > 0:
                    print(f"\nYou have {guess_limit - guess_count} guess(es) left.\nTry again 😁.")

                else:
                    print(f"You have no guesses left.")

            else:
                print(f"Your guess is too low 😢.")

                if guess_limit - guess_count > 0:
                    print(f"\nYou have {guess_limit - guess_count} guess(es) left.\nTry again 😁.")

                else:
                    print(f"You have no guesses left.")

    else:
        print("\nSorry!!!\nGame Over.")
        print(f"\nThe answer is {value}")

    return


while user_diff_level > '3':
    print("\nERROR!!! WRONG OPTION")
    user_option = input("""
Choose Either: 1, 2 or 3.
1 ===> Weak 😁
2 ===> fairly strong 😐
3 ===> very strong 😫
Please Pick an Option:
""")

else:

    if user_diff_level == '1':
        random_value = difficulty.get('easy')
        guess_limit = 6
        value = random.randint(1, 10)
        count()

    elif user_diff_level == '2':
        random_value = difficulty.get('medium')
        guess_limit = 4
        value = random.randint(1, 20)
        count()

    elif user_diff_level == '3':
        random_value = difficulty.get('hard')
        guess_limit = 3
        value = random.randint(1, 50)
        count()
