import random


def count(diff_level):
    """
    This function uses are; if the user inputs a number and the user number is more or less than the value
    randomly generated by the program, the user will be informed.
    Also, the user will be informed on how many trials they have left.
    If the user trial finishes before the user gets the randomly generated value,
    the program will stop running, and will inform the user the game is over displaying
    the randomly generated value. If the user gets the randomly generated value before their trial ends,
    the program also stops and inform the user that they won.
    """
    if diff_level == 1:
        # easy
        guess_limit = 6
        value = random.randint(1, 10)

    elif diff_level == 2:
        # medium
        guess_limit = 4
        value = random.randint(1, 20)

    elif diff_level == 3:
        # hard
        guess_limit = 3
        value = random.randint(1, 50)

    else:
        print(f"\nInvalid difficulty level: {diff_level}")
        return

    guess_count = 0

    while guess_count < guess_limit:
        user_guess = int(input("\nGuess the number: "))
        guess_count += 1

        if user_guess == value:
            print("\nHurray!!!\nYou won.")
            break

        elif user_guess != value:
            print("\nWrong!!!")

            if user_guess > value:
                print("Your guess is too high 😢.")

                if guess_limit - guess_count > 0:
                    print(f"\nYou have {guess_limit - guess_count} guess(es) left.\nTry again 😁.")

                else:
                    print(f"You have no guesses left.")

            else:
                print(f"Your guess is too low 😢.")

                if guess_limit - guess_count > 0:
                    print(f"\nYou have {guess_limit - guess_count} guess(es) left.\nTry again 😁.")

                else:
                    print(f"You have no guesses left.")
    else:
        print("\nSorry!!!\nGame Over.")
        print(f"\nThe answer is {value}")

    return


difficulty = {1: 'easy', 2: 'medium', 3: 'hard' }
random_value = ''
game = True

while game:
    user_diff_level = int(input("""
Please select 1, 2 or 3 or 0 to exit game.
1 ===> Easy 😁
2 ===> Medium 😐
3 ===> Hard 😫
Select an option:
"""))

    if user_diff_level in difficulty.keys():
        # start game
        count(user_diff_level)
        break

    elif user_diff_level == 0:
        # exit
        print("\nThanks for playing. Goodbye!")
        game = False

    else:
        print("\nERROR!!! WRONG OPTION\n\n")


